project_id = "gppoaaekwbvlshyxjsqe"

[auth]
  additional_redirect_urls = ["https://fieldlogapp.lovable.app/reset-password"]
  site_url = "https://fieldlogapp.lovable.app"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
