// Shared PDF generation for FieldLog reports.
// Multi-section: each section starts on a fresh page (hard page break).
//
// TEMPORARY: Backup Log timestamps render in DEFAULT_BACKUP_TZ
// (America/Los_Angeles) because the current App Store build does not yet
// pass the user's IANA timezone to the backend. Replace with client-provided
// timezone in the next App Store update — buildBackupLog already accepts
// an optional `timezone` argument.

export const DEFAULT_BACKUP_TZ = "America/Los_Angeles";

export const SENTINEL_TRANSCRIPTS = [
  "Recording too short for reliable transcription.",
  "No usable audio detected.",
  "Unclear or no speech detected.",
  "Unreliable transcription — excluded from report.",
];

export function isSentinel(transcript: string | null | undefined): boolean {
  if (!transcript) return true;
  return SENTINEL_TRANSCRIPTS.includes(transcript.trim());
}

export interface PdfSection {
  content: string;
}

/**
 * Generate a PDF from one or more sections.
 * Each section begins on a fresh page (hard page break between sections).
 * Footer "Generated by FieldLog" appears on every page.
 */
export function generatePdfBytes(sections: PdfSection[]): Uint8Array {
  const pageHeight = 842;
  const pageWidth = 595;
  const margin = 50;
  const lineHeight = 14;
  const maxCharsPerLine = 80;
  const footerReserve = 30;
  const usableHeight = pageHeight - 2 * margin - footerReserve;
  const linesPerPage = Math.floor(usableHeight / lineHeight);

  const sectionList = sections.length > 0 ? sections : [{ content: "" }];
  const pages: string[][] = [];

  for (const section of sectionList) {
    const rawLines = (section.content ?? "").split("\n");
    const wrappedLines: string[] = [];
    for (const line of rawLines) {
      if (line.length === 0) {
        wrappedLines.push("");
        continue;
      }
      let remaining = line;
      while (remaining.length > maxCharsPerLine) {
        let breakAt = remaining.lastIndexOf(" ", maxCharsPerLine);
        if (breakAt <= 0) breakAt = maxCharsPerLine;
        wrappedLines.push(remaining.substring(0, breakAt));
        remaining = remaining.substring(breakAt).trimStart();
      }
      wrappedLines.push(remaining);
    }

    if (wrappedLines.length === 0) {
      pages.push([""]);
      continue;
    }

    for (let i = 0; i < wrappedLines.length; i += linesPerPage) {
      pages.push(wrappedLines.slice(i, i + linesPerPage));
    }
  }

  if (pages.length === 0) pages.push([""]);

  const esc = (s: string) =>
    s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  let objCount = 0;
  const objects: string[] = [];
  const offsets: number[] = [];

  const addObj = (content: string) => {
    objCount++;
    objects.push(`${objCount} 0 obj\n${content}\nendobj\n`);
    return objCount;
  };

  addObj(`<< /Type /Catalog /Pages 2 0 R >>`);

  const courierFontId = 3;
  const helveticaFontId = 4;

  const pageObjIds: number[] = [];
  for (let i = 0; i < pages.length; i++) {
    pageObjIds.push(5 + i * 2);
  }

  addObj(
    `<< /Type /Pages /Kids [${pageObjIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`
  );
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`);
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  const footerText = "Generated by FieldLog";
  const footerX = pageWidth - 140;
  const footerY = 16;

  for (let p = 0; p < pages.length; p++) {
    const pageLines = pages[p];
    const contentObjId = 5 + p * 2 + 1;

    addObj(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentObjId} 0 R /Resources << /Font << /F1 ${courierFontId} 0 R /F2 ${helveticaFontId} 0 R >> >> >>`
    );

    const textOps: string[] = [];
    textOps.push("BT");
    textOps.push(`/F1 10 Tf`);
    const y = pageHeight - margin;
    textOps.push(`${margin} ${y} Td`);

    for (const line of pageLines) {
      textOps.push(`(${esc(line)}) Tj`);
      textOps.push(`0 -${lineHeight} Td`);
    }
    textOps.push("ET");

    textOps.push("BT");
    textOps.push(`/F2 7 Tf`);
    textOps.push(`0.6 0.6 0.6 rg`);
    textOps.push(`${footerX} ${footerY} Td`);
    textOps.push(`(${esc(footerText)}) Tj`);
    textOps.push("ET");

    const stream = textOps.join("\n");
    addObj(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  }

  let pdf = "%PDF-1.4\n";
  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += objects[i];
  }

  const xrefOffset = pdf.length;
  pdf += "xref\n";
  pdf += `0 ${objCount + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += "trailer\n";
  pdf += `<< /Size ${objCount + 1} /Root 1 0 R >>\n`;
  pdf += "startxref\n";
  pdf += `${xrefOffset}\n`;
  pdf += "%%EOF\n";

  return new TextEncoder().encode(pdf);
}

/**
 * Format a UTC timestamp as "h:mm AM/PM" in the given IANA timezone.
 */
function formatLocalTime(isoUtc: string, timezone: string): string {
  try {
    return new Date(isoUtc).toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
      timeZone: timezone,
    });
  } catch {
    return new Date(isoUtc).toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
      timeZone: DEFAULT_BACKUP_TZ,
    });
  }
}

export interface VoiceLogForBackup {
  recorded_at: string;
  transcript: string | null;
}

/**
 * Build the Backup Log section content from voice logs.
 * - Excludes sentinel/unusable transcripts (only logs that contributed to the report).
 * - Sorts by recorded_at ascending.
 * - Timestamps render in the provided IANA timezone (defaults to America/Los_Angeles).
 */
export function buildBackupLog(
  logs: VoiceLogForBackup[],
  timezone: string = DEFAULT_BACKUP_TZ
): string {
  const tz = timezone || DEFAULT_BACKUP_TZ;
  const usable = (logs || [])
    .filter((l) => l && l.transcript && !isSentinel(l.transcript))
    .slice()
    .sort(
      (a, b) =>
        new Date(a.recorded_at).getTime() - new Date(b.recorded_at).getTime()
    );

  const header = "BACKUP LOG\nSource voice notes — verbatim transcripts\n";

  if (usable.length === 0) {
    return `${header}\nNo voice notes available.`;
  }

  const blocks = usable.map((log) => {
    const time = formatLocalTime(log.recorded_at, tz);
    return `${time} — Voice Note\n${(log.transcript || "").trim()}`;
  });

  return `${header}\n${blocks.join("\n\n")}`;
}
