import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SENTINEL_TRANSCRIPTS = [
  "Recording too short for reliable transcription.",
  "No usable audio detected.",
  "Unclear or no speech detected.",
  "Unreliable transcription — excluded from report.",
];

function isSentinel(transcript: string): boolean {
  return SENTINEL_TRANSCRIPTS.includes(transcript.trim());
}

// Minimal PDF generator: produces a valid PDF with text content
function generatePdfBytes(title: string, content: string): Uint8Array {
  const lines = content.split("\n");
  const pageHeight = 842;
  const pageWidth = 595;
  const margin = 50;
  const lineHeight = 14;
  const maxCharsPerLine = 80;
  const footerReserve = 30;
  const usableHeight = pageHeight - 2 * margin - footerReserve;
  const linesPerPage = Math.floor(usableHeight / lineHeight);

  const wrappedLines: string[] = [];
  for (const line of lines) {
    if (line.length === 0) { wrappedLines.push(""); continue; }
    let remaining = line;
    while (remaining.length > maxCharsPerLine) {
      let breakAt = remaining.lastIndexOf(" ", maxCharsPerLine);
      if (breakAt <= 0) breakAt = maxCharsPerLine;
      wrappedLines.push(remaining.substring(0, breakAt));
      remaining = remaining.substring(breakAt).trimStart();
    }
    wrappedLines.push(remaining);
  }

  const pages: string[][] = [];
  for (let i = 0; i < wrappedLines.length; i += linesPerPage) {
    pages.push(wrappedLines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push([""]);

  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  let objCount = 0;
  const objects: string[] = [];
  const offsets: number[] = [];

  const addObj = (content: string) => {
    objCount++;
    objects.push(`${objCount} 0 obj\n${content}\nendobj\n`);
    return objCount;
  };

  // Obj 1: Catalog
  addObj(`<< /Type /Catalog /Pages 2 0 R >>`);

  const courierFontId = 3;
  const helveticaFontId = 4;

  // Page objects start at obj 5, each page = 2 objs (page + content stream)
  const pageObjIds: number[] = [];
  for (let i = 0; i < pages.length; i++) {
    pageObjIds.push(5 + i * 2);
  }

  // Obj 2: Pages
  addObj(`<< /Type /Pages /Kids [${pageObjIds.map(id => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`);
  // Obj 3: Courier font (body text)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`);
  // Obj 4: Helvetica font (footer text)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  // Footer positioning: bottom-right corner
  const footerText = "Generated by SiteLog";
  const footerX = pageWidth - 140;
  const footerY = 16;

  for (let p = 0; p < pages.length; p++) {
    const pageLines = pages[p];
    const contentObjId = 5 + p * 2 + 1;

    addObj(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentObjId} 0 R /Resources << /Font << /F1 ${courierFontId} 0 R /F2 ${helveticaFontId} 0 R >> >> >>`);

    const textOps: string[] = [];
    // Body text
    textOps.push("BT");
    textOps.push(`/F1 10 Tf`);
    const y = pageHeight - margin;
    textOps.push(`${margin} ${y} Td`);

    for (const line of pageLines) {
      textOps.push(`(${esc(line)}) Tj`);
      textOps.push(`0 -${lineHeight} Td`);
    }
    textOps.push("ET");

    // Footer text — fixed position, every page
    textOps.push("BT");
    textOps.push(`/F2 7 Tf`);
    textOps.push(`0.6 0.6 0.6 rg`);
    textOps.push(`${footerX} ${footerY} Td`);
    textOps.push(`(${esc(footerText)}) Tj`);
    textOps.push("ET");

    const stream = textOps.join("\n");
    addObj(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  }

  let pdf = "%PDF-1.4\n";
  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += objects[i];
  }

  const xrefOffset = pdf.length;
  pdf += "xref\n";
  pdf += `0 ${objCount + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += "trailer\n";
  pdf += `<< /Size ${objCount + 1} /Root 1 0 R >>\n`;
  pdf += "startxref\n";
  pdf += `${xrefOffset}\n`;
  pdf += "%%EOF\n";

  return new TextEncoder().encode(pdf);
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { log_ids, user_id, project_name, report_date: inputReportDate } = await req.json();
    const projectName = (project_name || "").trim() || "Untitled Project";

    if (!log_ids || !Array.isArray(log_ids) || log_ids.length === 0) {
      return new Response(
        JSON.stringify({ error: "log_ids array is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!user_id) {
      return new Response(
        JSON.stringify({ error: "user_id is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const lovableApiKey = Deno.env.get("LOVABLE_API_KEY");

    if (!lovableApiKey) {
      return new Response(
        JSON.stringify({ error: "LOVABLE_API_KEY not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch user email
    const { data: userData, error: userError } = await supabase
      .from("users")
      .select("email")
      .eq("id", user_id)
      .single();

    if (userError || !userData) {
      return new Response(
        JSON.stringify({ error: "User not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const userEmail = userData.email;

    // Fetch logs
    const { data: logs, error: logsError } = await supabase
      .from("voice_logs")
      .select("*")
      .in("id", log_ids)
      .order("recorded_at", { ascending: true });

    if (logsError) throw logsError;
    if (!logs || logs.length === 0) {
      return new Response(
        JSON.stringify({ error: "No logs found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Process logs: transcribe or skip based on guardrails
    const transcripts: string[] = [];

    for (const log of logs) {
      // --- GUARDRAIL 1: Duration too short ---
      if (log.duration_seconds < 3) {
        const sentinel = "Recording too short for reliable transcription.";
        console.log(`[GUARD] Log ${log.id}: duration ${log.duration_seconds}s < 3s — skipping transcription`);
        await supabase.from("voice_logs").update({ transcript: sentinel, status: "skipped" }).eq("id", log.id);
        continue; // sentinel — excluded from report
      }

      // If already transcribed, apply sanity check before including
      if (log.transcript) {
        // Check if it's a sentinel
        if (isSentinel(log.transcript)) {
          console.log(`[GUARD] Log ${log.id}: existing sentinel transcript — excluding`);
          continue;
        }

        // Sanity check: words-per-second ratio
        const wordCount = log.transcript.split(/\s+/).filter((w: string) => w.length > 0).length;
        const wps = wordCount / Math.max(log.duration_seconds, 1);
        if (wps > 5) {
          const sentinel = "Unreliable transcription — excluded from report.";
          console.log(`[GUARD] Log ${log.id}: ${wordCount} words in ${log.duration_seconds}s (${wps.toFixed(1)} wps) — unreliable`);
          await supabase.from("voice_logs").update({ transcript: sentinel, status: "unreliable" }).eq("id", log.id);
          continue;
        }

        transcripts.push(log.transcript);

        // Upload existing transcript to storage
        const logDate = new Date(log.recorded_at).toISOString().split("T")[0];
        const txtPath = `${logDate}/${userEmail}/${log.id}.txt`;
        await supabase.storage.from("transcripts").upload(txtPath, new TextEncoder().encode(log.transcript), {
          contentType: "text/plain",
          upsert: true,
        });
        continue;
      }

      // --- Need to transcribe ---
      await supabase.from("voice_logs").update({ status: "transcribing" }).eq("id", log.id);

      const { data: audioData, error: downloadError } = await supabase.storage
        .from("recordings")
        .download(log.audio_path);

      if (downloadError || !audioData) {
        console.error("Failed to download audio:", downloadError);
        await supabase.from("voice_logs").update({ status: "error" }).eq("id", log.id);
        continue;
      }

      const arrayBuffer = await audioData.arrayBuffer();

      // --- GUARDRAIL 2: Audio file too small ---
      if (arrayBuffer.byteLength < 1024) {
        const sentinel = "No usable audio detected.";
        console.log(`[GUARD] Log ${log.id}: audio size ${arrayBuffer.byteLength} bytes < 1KB — skipping`);
        await supabase.from("voice_logs").update({ transcript: sentinel, status: "skipped" }).eq("id", log.id);
        continue;
      }

      const bytes = new Uint8Array(arrayBuffer);
      let binary = "";
      const chunkSize = 8192;
      for (let i = 0; i < bytes.length; i += chunkSize) {
        binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
      }
      const base64Audio = btoa(binary);

      const transcribeResponse = await fetch(
        "https://ai.gateway.lovable.dev/v1/chat/completions",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${lovableApiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash",
            messages: [
              {
                role: "system",
                content: `You are a verbatim transcription engine. Transcribe ONLY speech that is clearly audible.
Rules:
- If no speech is detected, respond EXACTLY: "Unclear or no speech detected."
- If speech is partially unclear, transcribe only the clear parts.
- Do NOT invent, infer, or fabricate any content.
- Do NOT generate plausible filler text.
- Do NOT add names, dates, locations, or details that are not clearly spoken.
- Output ONLY what was clearly spoken — nothing more.`,
              },
              {
                role: "user",
                content: [
                  { type: "input_audio", input_audio: { data: base64Audio, format: "webm" } },
                  { type: "text", text: "Transcribe this audio. If no clear speech is present, respond exactly: \"Unclear or no speech detected.\"" },
                ],
              },
            ],
          }),
        }
      );

      if (!transcribeResponse.ok) {
        const errText = await transcribeResponse.text();
        console.error("Transcription failed:", transcribeResponse.status, errText);

        if (transcribeResponse.status === 429) {
          return new Response(
            JSON.stringify({ error: "Rate limited. Please try again in a moment." }),
            { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }
        if (transcribeResponse.status === 402) {
          return new Response(
            JSON.stringify({ error: "AI credits exhausted." }),
            { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        await supabase.from("voice_logs").update({ status: "error" }).eq("id", log.id);
        continue;
      }

      const transcribeResult = await transcribeResponse.json();
      let transcript = transcribeResult.choices?.[0]?.message?.content?.trim() || "";

      // --- GUARDRAIL 3: Post-transcription sanity check ---
      if (transcript && !isSentinel(transcript)) {
        const wordCount = transcript.split(/\s+/).filter((w: string) => w.length > 0).length;
        const wps = wordCount / Math.max(log.duration_seconds, 1);
        if (wps > 5) {
          console.log(`[GUARD] Log ${log.id}: transcription produced ${wordCount} words for ${log.duration_seconds}s (${wps.toFixed(1)} wps) — marking unreliable`);
          transcript = "Unreliable transcription — excluded from report.";
          await supabase.from("voice_logs").update({ transcript, status: "unreliable" }).eq("id", log.id);
          continue;
        }
      }

      await supabase.from("voice_logs").update({ transcript, status: "transcribed" }).eq("id", log.id);

      // Only include non-sentinel transcripts
      if (!isSentinel(transcript)) {
        transcripts.push(transcript);
      }

      // Upload transcript to storage
      const logDate = new Date(log.recorded_at).toISOString().split("T")[0];
      const txtPath = `${logDate}/${userEmail}/${log.id}.txt`;
      await supabase.storage.from("transcripts").upload(txtPath, new TextEncoder().encode(transcript), {
        contentType: "text/plain",
        upsert: true,
      });
    }

    // --- If no valid transcripts, return empty report ---
    if (transcripts.length === 0) {
      const emptyReport = "DAILY SITE REPORT\n\nNo activities reported. No usable field logs recorded.\n\n— End of Report —";

      const reportDate = inputReportDate || new Date().toISOString().split("T")[0];
      const pdfBytes = generatePdfBytes(`SiteLog Daily Report — ${projectName}`, emptyReport);
      const sanitizedName = projectName.replace(/[^a-zA-Z0-9 \-]/g, "").trim().replace(/\s+/g, " ");
      const pdfPath = `${reportDate}/${sanitizedName}_Daily Report_${reportDate}.pdf`;

      await supabase.storage.from("report-pdfs").upload(pdfPath, pdfBytes, {
        contentType: "application/pdf",
        upsert: true,
      });

      const pdfUrl = `${supabaseUrl}/storage/v1/object/public/report-pdfs/${pdfPath}`;

      const { data: existingReport } = await supabase
        .from("daily_reports")
        .select("id")
        .eq("user_id", user_id)
        .eq("report_date", reportDate)
        .eq("project_name", projectName)
        .maybeSingle();

      let report;
      if (existingReport) {
        const { data, error } = await supabase
          .from("daily_reports")
          .update({ content: emptyReport, log_ids, pdf_url: pdfUrl, user_email: userEmail, project_name: projectName })
          .eq("id", existingReport.id)
          .select()
          .single();
        if (error) throw error;
        report = data;
      } else {
        const { data, error } = await supabase
          .from("daily_reports")
          .insert({ content: emptyReport, log_ids, report_date: reportDate, user_id, pdf_url: pdfUrl, user_email: userEmail, project_name: projectName })
          .select()
          .single();
        if (error) throw error;
        report = data;
      }

      return new Response(JSON.stringify({ report: { ...report, pdf_url: pdfUrl } }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Generate report with trusted transcripts only
    const reportDate = inputReportDate || new Date().toISOString().split("T")[0];
    const reportDateObj = inputReportDate ? new Date(inputReportDate + "T00:00:00") : new Date();
    const todayStr = reportDateObj.toLocaleDateString("en-US", {
      weekday: "long", month: "long", day: "numeric", year: "numeric",
    });

    const reportResponse = await fetch(
      "https://ai.gateway.lovable.dev/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${lovableApiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3-flash-preview",
          messages: [
            {
              role: "system",
              content: `You are a construction daily report generator. You produce formal, structured daily site reports from voice log transcriptions.

STRICT GROUNDING RULES:
- ONLY include information explicitly stated in the transcripts.
- NEVER infer, fabricate, or embellish names, dates, weather, activities, or events.
- If a section has no relevant transcript data, write "Not reported."
- Do NOT generate a plausible construction narrative — report ONLY what was said.
- Do NOT add details that sound realistic but were not in the transcripts.
- If a transcript is vague or incomplete, report it as-is — do not fill gaps.

Output format:
DAILY SITE REPORT — [DATE]
PROJECT: [PROJECT NAME]

WEATHER & CONDITIONS:
(Only if explicitly mentioned in transcripts, otherwise "Not reported")

WORK PERFORMED:
- Only activities explicitly described in transcripts
- If none mentioned, write "Not reported"

MATERIALS & EQUIPMENT:
- Only items explicitly mentioned or "Not reported"

PERSONNEL:
- Only names/trades explicitly mentioned or "Not reported"

SAFETY OBSERVATIONS:
- Only safety items explicitly mentioned or "Not reported"

ISSUES / DELAYS:
- Only problems explicitly mentioned or "Not reported"

NOTES:
- Any additional context directly from transcripts

— End of Report —

Be factual. No embellishment. This is documentation-grade output.`,
            },
            {
              role: "user",
              content: `Generate a daily site report for ${todayStr}.\nPROJECT: ${projectName}\n\nVoice log transcriptions (${transcripts.length} verified logs):\n\n${transcripts
                .map((t, i) => `--- Log ${i + 1} ---\n${t}`)
                .join("\n\n")}`,
            },
          ],
        }),
      }
    );

    if (!reportResponse.ok) {
      const errText = await reportResponse.text();
      console.error("Report generation failed:", reportResponse.status, errText);
      return new Response(
        JSON.stringify({ error: "Failed to generate report" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const reportResult = await reportResponse.json();
    const reportContent = reportResult.choices?.[0]?.message?.content?.trim() || "";

    // Generate PDF
    const reportDate = new Date().toISOString().split("T")[0];
    const pdfBytes = generatePdfBytes(`SiteLog Daily Report — ${projectName} — ${todayStr}`, reportContent);
    const sanitizedName = projectName.replace(/[^a-zA-Z0-9 \-]/g, "").trim().replace(/\s+/g, " ");
    const pdfPath = `${reportDate}/${sanitizedName}_Daily Report_${reportDate}.pdf`;

    const { error: pdfUploadError } = await supabase.storage
      .from("report-pdfs")
      .upload(pdfPath, pdfBytes, {
        contentType: "application/pdf",
        upsert: true,
      });

    if (pdfUploadError) {
      console.error("PDF upload failed:", pdfUploadError);
    }

    const pdfUrl = `${supabaseUrl}/storage/v1/object/public/report-pdfs/${pdfPath}`;

    // Upsert daily_reports
    const { data: existingReport } = await supabase
      .from("daily_reports")
      .select("id")
      .eq("user_id", user_id)
      .eq("report_date", reportDate)
      .maybeSingle();

    let report;
    if (existingReport) {
      const { data, error } = await supabase
        .from("daily_reports")
        .update({ content: reportContent, log_ids, pdf_url: pdfUrl, user_email: userEmail })
        .eq("id", existingReport.id)
        .select()
        .single();
      if (error) throw error;
      report = data;
    } else {
      const { data, error } = await supabase
        .from("daily_reports")
        .insert({ content: reportContent, log_ids, report_date: reportDate, user_id, pdf_url: pdfUrl, user_email: userEmail })
        .select()
        .single();
      if (error) throw error;
      report = data;
    }

    // Upsert admin_reports
    const { data: existingAdmin } = await supabase
      .from("admin_reports")
      .select("id, status")
      .eq("user_id", user_id)
      .eq("report_date", reportDate)
      .maybeSingle();

    if (existingAdmin) {
      const updateData: Record<string, string> = {
        pdf_url: pdfUrl,
        user_email: userEmail,
        project_name: projectName,
      };
      if (existingAdmin.status !== "sent") {
        updateData.status = "pending_sent";
      }
      await supabase.from("admin_reports").update(updateData).eq("id", existingAdmin.id);
    } else {
      await supabase.from("admin_reports").insert({
        user_id,
        user_email: userEmail,
        report_date: reportDate,
        pdf_url: pdfUrl,
        project_name: projectName,
        status: "pending_sent",
      });
    }

    return new Response(JSON.stringify({ report: { ...report, pdf_url: pdfUrl } }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-report error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
