import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function generatePdfBytes(title: string, content: string): Uint8Array {
  const lines = content.split("\n");
  const pageHeight = 842;
  const pageWidth = 595;
  const margin = 50;
  const lineHeight = 14;
  const maxCharsPerLine = 80;
  const footerReserve = 30;
  const usableHeight = pageHeight - 2 * margin - footerReserve;
  const linesPerPage = Math.floor(usableHeight / lineHeight);

  const wrappedLines: string[] = [];
  for (const line of lines) {
    if (line.length === 0) { wrappedLines.push(""); continue; }
    let remaining = line;
    while (remaining.length > maxCharsPerLine) {
      let breakAt = remaining.lastIndexOf(" ", maxCharsPerLine);
      if (breakAt <= 0) breakAt = maxCharsPerLine;
      wrappedLines.push(remaining.substring(0, breakAt));
      remaining = remaining.substring(breakAt).trimStart();
    }
    wrappedLines.push(remaining);
  }

  const pages: string[][] = [];
  for (let i = 0; i < wrappedLines.length; i += linesPerPage) {
    pages.push(wrappedLines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push([""]);

  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  let objCount = 0;
  const objects: string[] = [];
  const offsets: number[] = [];

  const addObj = (content: string) => {
    objCount++;
    objects.push(`${objCount} 0 obj\n${content}\nendobj\n`);
    return objCount;
  };

  addObj(`<< /Type /Catalog /Pages 2 0 R >>`);

  const courierFontId = 3;
  const helveticaFontId = 4;

  const pageObjIds: number[] = [];
  for (let i = 0; i < pages.length; i++) {
    pageObjIds.push(5 + i * 2);
  }

  addObj(`<< /Type /Pages /Kids [${pageObjIds.map(id => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`);
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`);
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  const footerText = "Generated by FieldLog";
  const footerX = pageWidth - 140;
  const footerY = 16;

  for (let p = 0; p < pages.length; p++) {
    const pageLines = pages[p];
    const contentObjId = 5 + p * 2 + 1;

    addObj(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentObjId} 0 R /Resources << /Font << /F1 ${courierFontId} 0 R /F2 ${helveticaFontId} 0 R >> >> >>`);

    const textOps: string[] = [];
    textOps.push("BT");
    textOps.push(`/F1 10 Tf`);
    const y = pageHeight - margin;
    textOps.push(`${margin} ${y} Td`);

    for (const line of pageLines) {
      textOps.push(`(${esc(line)}) Tj`);
      textOps.push(`0 -${lineHeight} Td`);
    }
    textOps.push("ET");

    textOps.push("BT");
    textOps.push(`/F2 7 Tf`);
    textOps.push(`0.6 0.6 0.6 rg`);
    textOps.push(`${footerX} ${footerY} Td`);
    textOps.push(`(${esc(footerText)}) Tj`);
    textOps.push("ET");

    const stream = textOps.join("\n");
    addObj(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  }

  let pdf = "%PDF-1.4\n";
  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += objects[i];
  }

  const xrefOffset = pdf.length;
  pdf += "xref\n";
  pdf += `0 ${objCount + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += "trailer\n";
  pdf += `<< /Size ${objCount + 1} /Root 1 0 R >>\n`;
  pdf += "startxref\n";
  pdf += `${xrefOffset}\n`;
  pdf += "%%EOF\n";

  return new TextEncoder().encode(pdf);
}

// Helper: resolve authenticated user_id from JWT
async function resolveUserId(req: Request, supabaseUrl: string, anonKey: string, serviceClient: any): Promise<{ user_id: string; error?: never } | { user_id?: never; error: Response }> {
  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) {
    return {
      error: new Response(JSON.stringify({ error: "Unauthorized — missing or invalid Authorization header" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }),
    };
  }

  const anonClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });

  const { data: authData, error: authError } = await anonClient.auth.getUser();
  if (authError || !authData?.user) {
    return {
      error: new Response(JSON.stringify({ error: "Unauthorized — invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }),
    };
  }

  const authUid = authData.user.id;
  const authEmail = authData.user.email;

  const { data: userData, error: userError } = await serviceClient
    .from("users")
    .select("id, email")
    .eq("auth_id", authUid)
    .maybeSingle();

  if (userError) {
    return {
      error: new Response(JSON.stringify({ error: "Failed to resolve user" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }),
    };
  }

  if (userData) return { user_id: userData.id };

  if (authEmail) {
    const { data: emailUser } = await serviceClient
      .from("users")
      .select("id, auth_id")
      .eq("email", authEmail)
      .maybeSingle();

    if (emailUser && !emailUser.auth_id) {
      await serviceClient.from("users").update({ auth_id: authUid }).eq("id", emailUser.id);
      return { user_id: emailUser.id };
    }
  }

  return {
    error: new Response(JSON.stringify({ error: "User not found" }), {
      status: 404,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    }),
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { project_name, report_date, content } = await req.json();

    const missing: string[] = [];
    if (!project_name) missing.push("project_name");
    if (!report_date) missing.push("report_date");
    if (!content) missing.push("content");

    if (missing.length > 0) {
      return new Response(
        JSON.stringify({ error: `Missing required fields: ${missing.join(", ")}` }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Resolve user_id from JWT
    const resolved = await resolveUserId(req, supabaseUrl, anonKey, supabase);
    if (resolved.error) return resolved.error;
    const user_id = resolved.user_id;

    // Generate PDF
    const sanitizedName = project_name.replace(/[^a-zA-Z0-9 \-]/g, "").trim().replace(/\s+/g, " ");
    const pdfTitle = `FieldLog Daily Report — ${project_name} — ${report_date}`;
    const pdfBytes = generatePdfBytes(pdfTitle, content);
    const pdfPath = `${report_date}/${sanitizedName}_Daily Report_${report_date}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from("report-pdfs")
      .upload(pdfPath, pdfBytes, { contentType: "application/pdf", upsert: true });

    if (uploadError) {
      console.error("PDF upload failed:", uploadError);
      return new Response(
        JSON.stringify({ error: "Failed to upload PDF" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const pdfUrl = `${supabaseUrl}/storage/v1/object/public/report-pdfs/${pdfPath}`;

    const { data: dailyRows } = await supabase
      .from("daily_reports")
      .select("id, created_at")
      .eq("user_id", user_id)
      .eq("report_date", report_date)
      .eq("project_name", project_name)
      .order("created_at", { ascending: false });

    let updatedDailyReport = false;
    if (dailyRows && dailyRows.length > 0) {
      await supabase
        .from("daily_reports")
        .update({ content, pdf_url: pdfUrl })
        .eq("id", dailyRows[0].id);
      updatedDailyReport = true;
    }

    const { data: adminRows } = await supabase
      .from("admin_reports")
      .select("id, status, created_at")
      .eq("user_id", user_id)
      .eq("report_date", report_date)
      .eq("project_name", project_name)
      .order("created_at", { ascending: false });

    let updatedAdminReport = false;
    if (adminRows && adminRows.length > 0) {
      const updateData: Record<string, string> = { pdf_url: pdfUrl };
      if (adminRows[0].status !== "sent") {
        updateData.status = "pending_sent";
      }
      await supabase.from("admin_reports").update(updateData).eq("id", adminRows[0].id);
      updatedAdminReport = true;
    }

    return new Response(
      JSON.stringify({ pdf_url: pdfUrl, updated_daily_report: updatedDailyReport, updated_admin_report: updatedAdminReport }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("regenerate-report-pdf error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
